"""
AIOS Emotion Aura Engine
========================
Listens to EIE state changes from the Nexus API and applies
real-time CSS variable updates + system-wide theming.

This is what makes AIOS *feel* alive — the entire interface
breathing with the user's emotional state.
"""

import json
import time
import threading
import subprocess
import requests
from pathlib import Path
from dataclasses import dataclass
from typing import Optional

TOKENS_PATH = Path(__file__).parent.parent / "themes" / "emotion_tokens.json"
NEXUS_STATUS_URL = "http://localhost:11435/api/status"
POLL_INTERVAL_SEC = 5


@dataclass
class EmotionState:
    label: str
    emoji: str
    aura_primary: str
    aura_secondary: str
    aura_glow: str
    pulse_speed_s: float
    glass_blur_px: int
    notification_threshold: str
    llm_tone_hint: str
    wallpaper_variant: str


class EmotionAura:
    """
    Polls the Nexus API for current EIE emotion state and
    propagates color + behaviour changes across the UI layer.
    """

    def __init__(self):
        with open(TOKENS_PATH) as f:
            self._tokens: dict = json.load(f)["emotions"]

        self._current: EmotionState = self._load_state("neutral")
        self._callbacks: list = []
        self._running = False
        self._thread: Optional[threading.Thread] = None

    # ── Public API ─────────────────────────────────────────────

    def start(self):
        """Start background polling for emotion state changes."""
        self._running = True
        self._thread = threading.Thread(target=self._poll_loop, daemon=True)
        self._thread.start()
        print(f"[EmotionAura] Started — current state: {self._current.label}")

    def stop(self):
        self._running = False
        if self._thread:
            self._thread.join(timeout=2)

    def register_callback(self, fn):
        """Register fn(EmotionState) to be called on state changes."""
        self._callbacks.append(fn)

    @property
    def current(self) -> EmotionState:
        return self._current

    def force_state(self, label: str):
        """Manually override emotion state (for testing)."""
        new_state = self._load_state(label)
        self._apply(new_state)

    # ── Internal ───────────────────────────────────────────────

    def _poll_loop(self):
        last_label = self._current.label
        while self._running:
            try:
                resp = requests.get(NEXUS_STATUS_URL, timeout=2)
                if resp.ok:
                    data = resp.json()
                    new_label = data.get("emotion", {}).get("state", "neutral")
                    if new_label != last_label:
                        new_state = self._load_state(new_label)
                        self._apply(new_state)
                        last_label = new_label
            except Exception:
                # Nexus not running yet — fall back to neutral
                pass
            time.sleep(POLL_INTERVAL_SEC)

    def _apply(self, state: EmotionState):
        self._current = state
        self._write_css_vars(state)
        self._set_gtk_accent(state.aura_primary)
        for cb in self._callbacks:
            try:
                cb(state)
            except Exception as e:
                print(f"[EmotionAura] Callback error: {e}")
        print(f"[EmotionAura] → {state.emoji}  {state.label}")

    def _load_state(self, label: str) -> EmotionState:
        t = self._tokens.get(label, self._tokens["neutral"])
        return EmotionState(
            label=label,
            emoji=t["emoji"],
            aura_primary=t["aura_primary"],
            aura_secondary=t["aura_secondary"],
            aura_glow=t["aura_glow"],
            pulse_speed_s=t["pulse_speed_s"],
            glass_blur_px=t["glass_blur_px"],
            notification_threshold=t["notification_threshold"],
            llm_tone_hint=t["llm_tone_hint"],
            wallpaper_variant=t["wallpaper_variant"],
        )

    def _write_css_vars(self, state: EmotionState):
        """
        Write a live-reload CSS override file that the dashboard
        and command bar pick up immediately via @import.
        """
        css = f"""/* AUTO-GENERATED by EmotionAura — do not edit */
:root {{
  --aura-primary:        {state.aura_primary};
  --aura-secondary:      {state.aura_secondary};
  --aura-glow:           {state.aura_glow};
  --aura-pulse-speed:    {state.pulse_speed_s}s;
  --aios-glass-blur:     {state.glass_blur_px}px;
}}
"""
        out = Path(__file__).parent.parent / "themes" / "aura_live.css"
        out.write_text(css)

    def _set_gtk_accent(self, hex_color: str):
        """
        Update GNOME accent color to match the emotion aura.
        Requires GNOME >= 45 with accent-color support.
        Only runs if gsettings is available.
        """
        try:
            subprocess.run(
                ["gsettings", "set", "org.gnome.desktop.interface",
                 "accent-color", hex_color],
                capture_output=True, timeout=1
            )
        except (FileNotFoundError, subprocess.TimeoutExpired):
            pass


# ── Singleton ──────────────────────────────────────────────────
aura = EmotionAura()

if __name__ == "__main__":
    aura.start()
    # Demo: cycle through emotion states
    for emo in ["focused", "stressed", "energized", "happy", "tired"]:
        input(f"Press Enter to switch to '{emo}'...")
        aura.force_state(emo)
